# Generated by Django 4.2.13 on 2024-05-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='first_name',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='city',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='last_name',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='record',
            name='address',
        ),
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
        migrations.RemoveField(
            model_name='record',
            name='zipcode',
        ),
    ]
